spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodymoody
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bono
    password: 1111
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
