name: be-ci
on:
  pull_request:
    branches:
      - dev-be
env:
  BUILD_FILE_PATH: ./be/gradlew
jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo "ğŸ‰ The job was automatically triggered by a event."
      - name: ë ˆí¬ì§€í† ë¦¬ë¥¼ ì²´í¬ì•„ì›ƒí•œë‹¤
        uses: actions/checkout@v4
      - name: ìë°”ë¥¼ ì„¤ì¹˜í•œë‹¤
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: ì‹¤í–‰ê¶Œí•œì„ ë¶€ì—¬í•œë‹¤
        run: chmod +x ${{ env.BUILD_FILE_PATH }}
      - name: ë¹Œë“œí•œë‹¤
        run: ${{ env.BUILD_FILE_PATH }} build

